plugins {
    id 'com.android.application'
}
android {
    namespace 'com.custom.browser'
    compileSdk 33
    defaultConfig {
        applicationId "com.custom.browser"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
}
dependencies {
}
